workflows:
  flutter-workflow:
    name: Flutter Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        PUB_CACHE: ~/.pub-cache
    scripts:
      - echo "Fetching Flutter dependencies..."
      - flutter pub get
      - echo "Building APK..."
      - flutter build apk --release
      - echo "Building iOS..."
      - flutter build ios --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
